<a href="https://colab.research.google.com/github/Derlis-1/Tareas-SI/blob/main/01_IntroPython__LedesmaDerlis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [10]:

porcentaje_supervivencia = df['Survived'].mean() * 100
print(f"Porcentaje de pasajeros que sobrevivieron: {porcentaje_supervivencia:.2f}%")

Porcentaje de pasajeros que sobrevivieron: 38.38%

In [11]:

porcentaje_parch = df['Parch'].value_counts(normalize=True) * 100
print("Porcentaje de pasajeros segun Parch (Padres/Hijos a bordo):")
print(porcentaje_parch)

print("\n--------------------------------------------------\n")


porcentaje_pclass = df['Pclass'].value_counts(normalize=True) * 100
print("Porcentaje de pasajeros segun Pclass (Clase del boleto):")
print(porcentaje_pclass)

Porcentaje de pasajeros segun Parch (Padres/Hijos a bordo):
Parch
0    76.094276
1    13.243547
2     8.978676
5     0.561167
3     0.561167
4     0.448934
6     0.112233
Name: proportion, dtype: float64

--------------------------------------------------

Porcentaje de pasajeros segun Pclass (Clase del boleto):
Pclass
3    55.106622
1    24.242424
2    20.650954
Name: proportion, dtype: float64

In [12]:

conteo_genero = df['Sex'].value_counts()
print("Cantidad de pasajeros por genero:")
print(conteo_genero)

Cantidad de pasajeros por genero:
Sex
male      577
female    314
Name: count, dtype: int64

In [16]:
"""
### Conclusiones: Transformación de Datos en Información

En este ejercicio, se aplicó el ciclo fundamental de un Sistema de Información (SI) para procesar datos  del dataset *Titanic* y generar conocimiento útil. A través del análisis realizado, se pueden extraer las siguientes conclusiones:

1. Datos y la información: El dataset original contenía registros aislados que, por sí solos, carecían de significado inmediato. Al aplicar funciones como `.mean()` y `.value_counts()`, transformamos esos datos en indicadores clave, como el porcentaje de supervivencia (38.38%), lo cual ya constituye información valiosa para entender la magnitud del evento.
2. Contexto organizacional: El análisis de variables como el género (`Sex`) y la clase (`Pclass` / `Parch`) permite segmentar la información. Por ejemplo, observar que hubo una mayor cantidad de hombres que de mujeres a bordo ayuda a contextualizar las estadísticas de supervivencia bajo las políticas de evacuación de la época.
3. Utilidad de la herramienta: El uso de librerías como Pandas en un entorno de Colab facilita la manipulación de grandes volúmenes de datos de manera eficiente. Esto demuestra que la tecnología es un habilitador crítico para que los analistas puedan enfocarse en la interpretación de los resultados en lugar de la computación manual.

"""

'\n### Conclusiones: Transformación de Datos en Información\n\nEn este ejercicio, se aplicó el ciclo fundamental de un Sistema de Información (SI) para procesar datos crudos del dataset *Titanic* y generar conocimiento útil. A través del análisis realizado, se pueden extraer las siguientes conclusiones:\n\n1. **Datos vs. Información:** El dataset original contenía registros aislados que, por sí solos, carecían de significado inmediato. Al aplicar funciones como `.mean()` y `.value_counts()`, transformamos esos datos en indicadores clave, como el porcentaje de supervivencia (38.38%), lo cual ya constituye información valiosa para entender la magnitud del evento.\n2. **Contexto Organizacional:** El análisis de variables como el género (`Sex`) y la clase (`Pclass` / `Parch`) permite segmentar la información. Por ejemplo, observar que hubo una mayor cantidad de hombres que de mujeres a bordo ayuda a contextualizar las estadísticas de supervivencia bajo las políticas de evacuación de la época.\n3. **Utilidad de la Herramienta:** El uso de librerías como Pandas en un entorno de Colab facilita la manipulación de grandes volúmenes de datos de manera eficiente. Esto demuestra que la tecnología es un habilitador crítico para que los analistas puedan enfocarse en la interpretación de los resultados en lugar de la computación manual.\n\nEn conclusión, el procesamiento de datos les otorga el contexto y la utilidad necesarios para que dejen de ser simples números y se conviertan en información estratégica para la toma de decisiones o el análisis histórico.\n'